version: '3.7'

services:

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db-if-example
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - 'db:/var/lib/postgresql/data'
    networks:
      - if-example

  api-if-example:
    build:
      context: .
    container_name: api-if-example
    ports:
      - 3001:8080
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - API_BASE_URL=http://localhost:8080
    depends_on:
      - postgres
    networks:
      - if-example

networks:
  if-example:
    driver: bridge

volumes:
  db:
